language: go

go:
  - 1.14.x

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows

script:
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build ./...